name: Publish Release

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --all-features

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup .cazan directory
        run: |
          mkdir -p .cazan/build
          echo "[]" > .cazan/build/assets.json
          echo "[]" > .cazan/build/assets.json.import-test
      - name: Test
        run: cargo test --all-features

  format_and_lint:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-features -- -D warnings

  publish:
    name: Publish
    needs: [build, test, format_and_lint]
    runs-on: ubuntu-latest
    environment:
      name: Deployment on crates.io
      url: https://crates.io/crates/cazan-utils

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Package
        run: cargo package --all-features
      - name: Publish
        run: cargo publish --all-features
        env:
          CRATES_IO_TOKEN: ${{ secrets.CAZAN_CRATES_IO_TOKEN }}
